projects:
    type: rest
    resource: DotHiv\APIBundle\Controller\ProjectController

dot_hiv_api_check_login_state:
    path: login_state
    methods: [ GET ]
    defaults: { _controller: DotHivAPIBundle:Security:checkLoginState }
