dothiv_api_domain_claim:
    pattern:  /domain/claim
    defaults:
        _controller: dothiv.api.controller.domain:claimAction
    methods: [POST]

dothiv_api_user_profile:
    pattern:  /user/{handle}
    defaults:
        _controller: dothiv.api.controller.user:profileAction
    methods: [GET]

dothiv_api_user_domains:
    pattern:  /user/{handle}/domains
    defaults:
        _controller: dothiv.api.controller.user:domainsAction
    methods: [GET]

dothiv_api_domain_banner_config_set:
    pattern:  /domain/{name}/banner
    defaults:
        _controller: dothiv.api.controller.banner:setConfigAction
    methods: [PUT]

dothiv_api_domain_banner_config_get:
    pattern:  /domain/{name}/banner
    defaults:
        _controller: dothiv.api.controller.banner:getConfigAction
    methods: [GET]
