projects:
    type: rest
    resource: DotHiv\APIBundle\Controller\ProjectController

user:
    type: rest
    resource: DotHiv\APIBundle\Controller\UserController

alternatives:
    type: rest
    resource: DotHiv\APIBundle\Controller\AlternativesController

domains:
    type: rest
    resource: DotHiv\APIBundle\Controller\DomainController

domainclaims:
    type: rest
    resource: DotHiv\APIBundle\Controller\DomainClaimController
