dothiv_api_domain_claim:
    pattern:  /domain/claim
    defaults:
        _controller: dothiv.api.controller.domain:claimAction
    methods: [POST]

dothiv_api_user_domains:
    pattern:  /user/domains
    defaults:
        _controller: dothiv.api.controller.user:domainsAction
    methods: [GET]
