parameters:
    cors_options:
        allow_origin: [ '^chrome-extension://', '^https?://(www\.)?%charitydomain%', '^https?://(www\.)?%registrydomain%', '^https?://localhost', '^https?://127.0.0.1' ]

services:
    dothiv.cors_listener:
        class: Dothiv\APIBundle\Listener\CORSListener
        tags: 
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 254 }
        arguments: [ '@event_dispatcher', %cors_options% ]
