parameters:
    cors_options:
        allow_origin: [ '^chrome-extension://', '^https?://(www\.)?%charitydomain%', '^https?://(www\.)?%registrydomain%', '^https?://localhost', '^https?://127.0.0.1' ]

services:
    security.authentication.success_handler:
        class: %security.authentication.success_handler.class%
        public: false
        arguments: ['@security.http_utils', '/', '@fos_rest.view_handler' ]

    security.authentication.failure_handler:
        class: %security.authentication.failure_handler.class%
        public: false
        arguments:  ['@http_kernel', '@security.http_utils', '', '@logger', '@translator', '@templating']

    # do the decoding of the body first in any case
    fos_rest.body_listener:
        class: FOS\RestBundle\EventListener\BodyListener
        tags: 
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 255 }
        arguments: [ '@fos_rest.decoder_provider' ]

    dothiv.cors_listener:
        class: Dothiv\APIBundle\Listener\CORSListener
        tags: 
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 254 }
        arguments: [ '@event_dispatcher', %cors_options% ]
