services:
    dothiv.admin.controller.page:
        class: Dothiv\AdminBundle\Controller\PageController
        arguments:
          - @templating

    dothiv.admin.controller.account:
        class: %dothiv.api.controller.account.class%
        arguments:
         - @dothiv.admin.service.user
         - @dothiv.repository.user
         - @serializer
         - @clock
