parameters:
    dothiv.admin.api.controller.stats.class: Dothiv\AdminBundle\Controller\StatsController
    dothiv.admin.api.controller.nonprofitregistration.class: Dothiv\AdminBundle\Controller\NonProfitRegistrationController
    dothiv.admin.api.controller.attachment.class: Dothiv\AdminBundle\Controller\AttachmentController

services:
    dothiv.admin.controller.page:
        class: Dothiv\AdminBundle\Controller\PageController
        arguments:
          - @templating

    dothiv.admin.api.controller.account:
        class: %dothiv.api.controller.account.class%
        arguments:
         - @dothiv.admin.service.user
         - @dothiv.repository.user
         - @serializer
         - @clock

    dothiv.admin.api.controller.stats:
        class: %dothiv.admin.api.controller.stats.class%
        arguments:
        - @dothiv.admin.service.stats
        - @serializer
        - @router

    dothiv.admin.api.controller.nonprofitregistration:
        class: %dothiv.admin.api.controller.nonprofitregistration.class%
        arguments:
        - @dothiv.business.service.nonprofitregistration
        - @dothiv.repository.nonprofitregistration
        - @dothiv.admin.transformer.nonprofitregistration
        - @dothiv.admin.transformer.paginatedlist
        - @serializer

    dothiv.admin.api.controller.attachment:
        class: %dothiv.admin.api.controller.attachment.class%
        arguments:
        - @dothiv.businessbundle.service.attachment
