dothiv_admin_app:
    path:     /
    defaults:
        _controller: dothiv.admin.controller.page:pageAction
        page: index

dothiv_admin_app_page:
    path:     /app/{page}.html
    defaults:
        _controller: dothiv.admin.controller.page:appPageAction

dothiv_admin_api_account_loginlink:
    path:  /api/account/loginLink
    defaults:
        _controller: dothiv.admin.api.controller.account:loginLinkAction
        _format: json
        _dothiv.ApiRequest: Dothiv\AdminBundle\Request\LoginLinkRequest
        locale: en
    methods: [POST]

# Stats
dothiv_admin_stats_list_reporters:
    path: /api/stats
    defaults:
        _controller: dothiv.admin.api.controller.stats:listReportersAction
        _format: json
    methods: [GET]

dothiv_admin_stats_get_reporter:
    path: /api/stats/{reporterId}
    defaults:
        _controller: dothiv.admin.api.controller.stats:getReporterAction
        _format: json
    methods: [GET]

dothiv_admin_stats_report:
    path: /api/stats/{reporterId}/report/{reportId}
    defaults:
        _controller: dothiv.admin.api.controller.stats:getReportAction
        _format: json
    methods: [GET]

# Non-profit registrations
dothiv_admin_nonprofit_list_registrations:
    path: /api/nonprofitregistration
    defaults:
        _controller: dothiv.admin.api.controller.nonprofitregistration:listItemsAction
        _format: json
    methods: [GET]

dothiv_admin_nonprofit_registration:
    path: /api/nonprofitregistration/{identifier}
    defaults:
        _controller: dothiv.admin.api.controller.nonprofitregistration:getItemAction
        _format: json
    methods: [GET]

# Domain registrations
dothiv_admin_domain_list_registrations:
    path: /api/domain
    defaults:
        _controller: dothiv.admin.api.controller.domain:listItemsAction
        _format: json
    methods: [GET]

dothiv_admin_domain_registration:
    path: /api/domain/{identifier}
    defaults:
        _controller: dothiv.admin.api.controller.domain:getItemAction
        _format: json
    methods: [GET]
    
dothiv_admin_domain_registration_update:
    path: /api/domain/{identifier}
    defaults:
        _controller: dothiv.admin.api.controller.domain:updateItemAction
        _format: json
    methods: [PATCH]

# Config
dothiv_admin_config_list:
    path: /api/config
    defaults:
        _controller: dothiv.admin.api.controller.config:listItemsAction
        _format: json
    methods: [GET]

dothiv_admin_config:
    path: /api/config/{identifier}
    defaults:
        _controller: dothiv.admin.api.controller.config:getItemAction
        _format: json
    methods: [GET]
    requirements:
        identifier: .+

dothiv_admin_config_update:
    path: /api/config/{identifier}
    defaults:
        _controller: dothiv.admin.api.controller.config:updateItemAction
        _format: json
    methods: [PATCH]
    requirements:
        identifier: .+
        property: .+
        
# History
dothiv_admin_history_list:
    path: /api/history/{entity}/{identifier}
    defaults:
        _controller: dothiv.admin.api.controller.history:listItemsAction
        _format: json
    methods: [GET]

dothiv_admin_history:
    path: /api/history/{entity}/{identifier}/{id}
    defaults:
        _controller: dothiv.admin.api.controller.history:getItemAction
        _format: json
    methods: [GET]

# Attachments
dothiv_admin_attachment:
    path: /api/attachment/{handle}
    defaults:
        _controller: dothiv.admin.api.controller.attachment:getAttachmentAction
    methods: [GET]

# Users
dothiv_admin_user:
    path: /api/user/{handle}
    defaults:
        _controller: dothiv.admin.api.controller.user:getUserAction
    methods: [GET]

# Registrars
dothiv_admin_registrar:
    path: /api/registrar/{identifier}
    defaults:
       _controller: dothiv.admin.api.controller.registrar:getItemAction
    methods: [GET]
