parameters:
    dothiv.admin.service.stats.class: Dothiv\AdminBundle\Service\StatsService
    dothiv.admin.service.mailer.login.class: Dothiv\AdminBundle\Service\Mailer\LoginLinkMailer
    dothiv.admin.transformer.nonprofitregistration.class: Dothiv\AdminBundle\Transformer\NonProfitRegistrationTransformer
    dothiv.admin.transformer.domain.class: Dothiv\AdminBundle\Transformer\DomainTransformer
    dothiv.admin.transformer.paginatedlist.class: Dothiv\AdminBundle\Transformer\PaginatedListTransformer
    dothiv.admin.transformer.attachment.class: Dothiv\AdminBundle\Transformer\AttachmentTransformer
    dothiv.admin.transformer.user.class: Dothiv\AdminBundle\Transformer\UserTransformer

services:
    dothiv.admin.service.mailer.login:
        class: %dothiv.admin.service.mailer.login.class%
        arguments:
        - @mailer
        - @router
        - 'dothiv_admin_app'
        - %email_from_address%
        - %email_from_name%
        tags:
            - { name: kernel.event_listener, event: dothiv.admin.loginlink.requested, method: onLoginLinkRequested }

    dothiv.admin.service.user:
        class: %dothiv.businessbundle.service.user.class%
        arguments:
        - @dothiv.repository.user
        - @dothiv.repository.user_token
        - @clock
        - @event_dispatcher
        - 'dothiv.admin.loginlink.requested'
        - "%charitydomain%"
        - %dothiv_business.link_request_wait%

    dothiv.admin.service.stats:
        class: %dothiv.admin.service.stats.class%

    dothiv.admin.transformer.nonprofitregistration:
        class: %dothiv.admin.transformer.nonprofitregistration.class%
        arguments:
        - @router
        - "dothiv_admin_nonprofit_registration"
        calls:
        - [setAttachmentTransformer, [@dothiv.admin.transformer.attachment]]
        - [setUserTransformer, [@dothiv.admin.transformer.user]]

    dothiv.admin.transformer.domain:
        class: %dothiv.admin.transformer.domain.class%
        arguments:
        - @router
        - "dothiv_admin_domain_registration"

    dothiv.admin.transformer.paginatedlist:
        class: %dothiv.admin.transformer.paginatedlist.class%
        arguments:
        - @router
        - ~

    dothiv.admin.transformer.attachment:
        class: %dothiv.admin.transformer.attachment.class%
        arguments:
        - @router
        - "dothiv_admin_attachment"
        calls:
        - [setSecurityContext, [@security.context]]

    dothiv.admin.transformer.user:
        class: %dothiv.admin.transformer.user.class%
        arguments:
        - @router
        - "dothiv_admin_user"
