parameters:
    dothiv.admin.service.mailer.login.class: Dothiv\AdminBundle\Service\Mailer\LoginLinkMailer

services:
    dothiv.admin.service.mailer.login:
        class: %dothiv.admin.service.mailer.login.class%
        arguments:
        - @mailer
        - @router
        - 'dothiv_admin_app'
        - %email_from_address%
        - %email_from_name%
        tags:
            - { name: kernel.event_listener, event: dothiv.admin.loginlink.requested, method: onLoginLinkRequested }
