language: php

php:
  - 5.4

before_script:
# install apache
  - sudo apt-get install apache2
  - sudo a2enmod actions
  - sudo a2enmod rewrite
  - echo "export PATH=/home/vagrant/.phpenv/bin:$PATH" | sudo tee -a /etc/apache2/envvars > /dev/null
  - echo "$(curl -fsSL https://raw.github.com/gist/16d751c979fdeb5a14e3/gistfile1.txt)" | sudo tee /etc/apache2/conf.d/phpconfig > /dev/null
  - echo "$(curl -fsSL https://raw.github.com/gist/2eb301570ed4a1f4c33d/gistfile1.txt)" | sed -e "s,PATH,`pwd`/web,g" | sudo tee /etc/apache2/sites-available/default > /dev/null
  - sudo service apache2 restart
# install karma
  - sudo apt-get install python-software-properties python g++ make software-properties-common
  - sudo add-apt-repository -y ppa:chris-lea/node.js
  - sudo apt-get update
  - sudo apt-get install nodejs
  - sudo npm install -g karma
# install dothiv
  - composer install
  - mysql -e 'create database dothiv;'
  - php app/console doctrine:schema:create

before_install:
# headless testing
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
# PHP testing
  - phpunit -c app
# Javascript testing
  - cd src/DotHiv/WebsiteCharityBundle/Resources/public
  - DISPLAY=:99.0 CHROME_BIN="/usr/bin/chromium-browser" ./scripts/e2e-test.sh
