language: php

php:
  - 5.4

before_script: composer install

script: 
  - phpunit -c app
  - cd src/DotHiv/WebsiteCharityBundle/Resources/public
  - CHROME_BIN="/usr/bin/chromium-browser" ./scripts/test.sh
