services:
    dothiv.base.web.controller.registry_page:
        class: Dothiv\BaseWebsiteBundle\Controller\PageController
        arguments:
          - @templating
          - @dothiv.websitebase.contentful.portals_content
          - "DothivRegistryWebsiteBundle"
