parameters:
    dothiv.websitebase.assetic.filter.ngmin.class: Dothiv\BaseWebsiteBundle\Assetic\Filter\NgMinFilter

services:
    dothiv.websitebase.assetic.filter.ngmin:
        class: %dothiv.websitebase.assetic.filter.ngmin.class%
        tags:
            - { name: assetic.filter, alias: ngmin }
        arguments: [%ngmin_bin%]

    dothiv.websitebase.assetic.filter.closureecma5:
        class: %assetic.filter.closure.jar.class%
        tags:
            - { name: assetic.filter, alias: closureecma5 }
        arguments: [%assetic.filter.closure.jar%, %assetic.filter.closure.java%]
        calls:
            - [ setTimeout, [%assetic.filter.closure.timeout%] ]
            - [ setCompilationLevel, [%assetic.filter.closure.compilation_level%] ]
            - [ setLanguage, ['ECMASCRIPT5'] ]

    dothiv.websitebase.translation.json_loader:
        class: Dothiv\BaseWebsiteBundle\Translation\JsonLoader
        tags:
            - { name: translation.loader, alias: json }
