parameters:
    dothiv.websitebase.assetic.filter.ngmin.class: Dothiv\BaseWebsiteBundle\Assetic\Filter\NgMinFilter
    dothiv.websitebase.contentful.content.class: Dothiv\BaseWebsiteBundle\Contentful\Content
    dothiv.websitebase.contentful.view_builder.class: Dothiv\BaseWebsiteBundle\Contentful\ViewBuilder

services:
    dothiv.websitebase.assetic.filter.ngmin:
        class: %dothiv.websitebase.assetic.filter.ngmin.class%
        tags:
            - { name: assetic.filter, alias: ngmin }
        arguments: [%ngmin_bin%]

    dothiv.websitebase.assetic.filter.closureecma5:
        class: %assetic.filter.closure.jar.class%
        tags:
            - { name: assetic.filter, alias: closureecma5 }
        arguments: [%assetic.filter.closure.jar%, %assetic.filter.closure.java%]
        calls:
            - [ setTimeout, [%assetic.filter.closure.timeout%] ]
            - [ setCompilationLevel, [%assetic.filter.closure.compilation_level%] ]
            - [ setLanguage, ['ECMASCRIPT5'] ]

    dothiv.websitebase.translation.json_loader:
        class: Dothiv\BaseWebsiteBundle\Translation\JsonLoader
        tags:
            - { name: translation.loader, alias: json }

    dothiv.websitebase.contentful.view_builder:
            class: %dothiv.websitebase.contentful.view_builder.class%
            arguments:
                - 'en'
                - @dothiv_contentful.content
                
    dothiv.websitebase.contentful.portals_content:
        class: %dothiv.websitebase.contentful.content.class%
        arguments:
            - @dothiv_contentful.content
            - @dothiv.websitebase.contentful.view_builder
            - %contenful_portals_space%
