parameters:
    dothiv.websitebase.twig.extension.date.class: Dothiv\BaseWebsiteBundle\Twig\Extension\DateTwigExtension
    dothiv.websitebase.twig.extension.shuffle.class: Dothiv\BaseWebsiteBundle\Twig\Extension\ShuffleTwigExtension
    dothiv.websitebase.twig.extension.money.class: Dothiv\BaseWebsiteBundle\Twig\Extension\MoneyTwigExtension

services:
    dothiv.websitebase.twig.extension.date:
        class: %dothiv.websitebase.twig.extension.date.class%
        tags:
         - { name: twig.extension }

    dothiv.websitebase.twig.extension.shuffle:
        class: %dothiv.websitebase.twig.extension.shuffle.class%
        tags:
         - { name: twig.extension }

    dothiv.websitebase.twig.extension.money:
        class: %dothiv.websitebase.twig.extension.money.class%
        tags:
         - { name: twig.extension }
        arguments:
         - @dothiv.websitebase.money_format
