parameters:
    dothiv.websitebase.twig.extension.contentful.class: Dothiv\BaseWebsiteBundle\Twig\Extension\ContentfulTwigExtension

services:
    dothiv.websitebase.twig.extension.contentful:
        class: %dothiv.websitebase.twig.extension.contentful.class%
        arguments:
         - @dothiv.websitebase.contentful.portals_content
        tags:
         - { name: twig.extension }
