services:
    dothiv.registry.web.controller.page:
        class: Dothiv\RegistryWebsiteBundle\Controller\PageController
        arguments:
          - @templating
          - @dothiv.websitebase.contentful.content
