services:
    dothiv.registry.web.controller.page:
        class: Dothiv\RegistryWebsiteBundle\Controller\PageController
        arguments:
          - @templating
          - @dothiv_contentful.adapter
          - %contentful.content_type.page%
