services:
    dothiv.registry.web.controller.registry_page:
        class: Dothiv\BaseWebsiteBundle\Controller\PageController
        arguments:
          - @templating
          - @dothiv.registry.contentful.registry_content
          - "DothivRegistryWebsiteBundle"
