parameters:
#    dothiv_registry_web.example.class: Dothiv\RegistryWebsiteBundle\Example

services:
#    dothiv_registry_web.example:
#        class: %dothiv_registry_web.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
