imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: doctrine_extensions.yml }

framework:
    #esi:             ~
    translator:      { enabled: true, fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        assets_version: %assets_version%
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    globals:
      facebook_app_id: %facebook_app_id%
      twitter_widget_id: %twitter_widget_id%
      countdown_start: 2014-06-21T00:00:00Z
      general_availability: 2014-08-26T00:00:00Z
      assets_version: %assets_version%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        ['DothivCharityWebsiteBundle', 'DothivRegistryWebsiteBundle', 'DothivAPIBundle', 'DothivTwitterBootstrapBundle', 'DothivAngularJsBundle']
    #java: /usr/bin/java
    filters:
        less:
            node: %node_bin%
            node_paths: [%node_modules%]
            apply_to: "\.less$"
        cssrewrite: ~
        closure:
            jar: "%kernel.root_dir%/Resources/java/closure/compiler.jar"
            compilation_level: SIMPLE_OPTIMIZATIONS
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        path:     %database_path%
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%
    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true
        mappings:
            translatable:
                type: annotation
                alias: Gedmo
                prefix: Gedmo\Translatable\Entity
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity"        

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

# Gregwar's form
gregwar_form: ~

dothiv_business:
    allowed_tlds:
      # - hiv
      ~

dothiv_base_website:
    thumbnails:
        - { label: 'person', width: 260, height: 300, thumbnail: true }
        - { label: 'supporter', width: 125, height: 125, exact: true }
        - { label: 'partner', width: 200, height: 100, exact: true }
        - { label: 'small', width: 200, height: 200 }
        - { label: 'medium', width: 400, height: 400 }
        - { label: 'large', width: 800, height: 800 }

dothiv_charity_website:
    features:
        - { name: howitworks, enabled: false }
        - { name: projects, enabled: false }
        - { name: profile, enabled: false }
        - { name: pinkbar_clickcounter, enabled: false }
        - { name: pinkbar_countdown, enabled: true }

parameters:
    # Email addresses 
    domain_email_sender_address: mail@click4life.hiv.dev

    # configure symfony security bundle to use our REST authentication classes.
    # this is required by the angular app authentication process (see http authentication interceptor)
    security.authentication.form_entry_point.class: Dothiv\APIBundle\Security\RestAuthenticationEntryPoint
    security.authentication.listener.form.class: Dothiv\APIBundle\Security\RestAuthenticationListener
    security.authentication.success_handler.class: Dothiv\APIBundle\Security\DothivAuthenticationSuccessHandler
    security.authentication.failure_handler.class: Dothiv\APIBundle\Security\RestAuthenticationFailureHandler
    security.logout.success_handler.class: Dothiv\APIBundle\Security\RestLogoutSuccessHandler
    security.logout_listener.class: Dothiv\APIBundle\Security\RestLogoutListener

    # listener that sets the users locale
    locale_listener.class: Dothiv\APIBundle\Listener\LocaleListener

    # handler for serialization of forms
    jms_serializer.form_error_handler.class: Dothiv\BusinessBundle\Serializer\FormHandler

    # Default HTTP cache lifetime for pages
    page_lifetime: 1800

