parameters:
    database_driver:   pdo_mysql
    database_host:     127.0.0.1
    database_port:     ~
    database_name:     dothiv
    database_user:     root
    database_password: ~

    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~

    locale:            en_US
    secret:            huhepUSpEpr2DReSwaqeTAT499r9traYEph33u3UH7ph3cr66AR4sTAfEduxekam

    charitydomain:     dothiv.bp
    companydomain:     registry.hiv

    # configure symfony security bundle to use our REST authentication classes.
    # this is required by the angular app authentication process (see http authentication interceptor)
    security.authentication.form_entry_point.class: DotHiv\APIBundle\Security\RestAuthenticationEntryPoint
    security.authentication.success_handler.class: DotHiv\APIBundle\Security\RestAuthenticationSuccessHandler
    security.authentication.failure_handler.class: DotHiv\APIBundle\Security\RestAuthenticationFailureHandler
