# security routing
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_security_check:
    pattern: /api/login
    defaults: { _controller: DotHivAPIBundle:Security:postLogin }
    methods: [ POST ]

dot_hiv_api_security_login:
    pattern: /api/login
    defaults: { _controller: DotHivAPIBundle:Security:getLogin }
    methods: [ GET ]

fos_user_security_logout:
    pattern: /api/login
    defaults: { _controller: DotHivAPIBundle:Security:deleteLogin }
    methods: [ DELETE ]

dot_hiv_security_options:
    pattern: /api/login
    defaults: { _controller: DotHivAPIBundle:Security:optionsLogin }
    methods: [ OPTIONS ]

dot_hiv_api_security_facebook_login_start:
    pattern: /api/login/facebook/start
    defaults: { _controller: DotHivAPIBundle:Security:facebookLoginStart }
    methods: [ GET ]

dot_hiv_api_security_facebook_login_return:
    pattern: /api/login/facebook/return
    defaults: { _controller: DotHivAPIBundle:Security:facebookLoginReturn }
    methods: [ GET ]

# facebook login routing
_security_check:
    pattern:  /login_check
    defaults: { _controller: DotHivAPIBundle:Security:postLogin }

_security_logout:
    pattern:  /logout
    defaults: { _controller: DotHivAPIBundle:Security:deleteLogin }

# API routing
dot_hiv_api:
    resource: "@DotHivAPIBundle/Resources/config/routing.yml"
    prefix:   /api/

# routing for charity website
dot_hiv_website_charity:
    host: %charitydomain%
    resource: "@DotHivWebsiteCharityBundle/Resources/config/routing.yml"
    prefix:   /

# routing for company website
dot_hiv_website_company:
    host: %companydomain%
    resource: "@DotHivWebsiteCompanyBundle/Resources/config/routing.yml"
    prefix:   /
