dot_hiv_website_company:
    resource: "@DotHivWebsiteCompanyBundle/Resources/config/routing.yml"
    prefix:   /

# FOSUserBundle security routing
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
# End of FOSUserBundle security routing

dot_hiv_website_charity:
    resource: "@DotHivWebsiteCharityBundle/Resources/config/routing.yml"
    prefix:   /

dot_hiv_api:
    resource: "@DotHivAPIBundle/Resources/config/routing.yml"
    prefix:   /api/


