# API routing
dothiv_api:
    resource: "@DothivAPIBundle/Resources/config/routing.yml"
    prefix:   /api/

# routing for charity website
dothiv_charity_web:
    resource: .
    type: charity_routes
    host: %charitydomain%
    prefix:   /

# routing for company website
dothiv_registry_web:
    host: %registrydomain%
    resource: "@DothivRegistryWebsiteBundle/Resources/config/routing.yml"
    prefix:   /
