jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_THIRDPARTY_LOGIN: ROLE_VOTER
        ROLE_FACEBOOK: ROLE_THIRDPARTY_LOGIN
        ROLE_GPLUS: ROLE_THIRDPARTY_LOGIN
        ROLE_LINKEDIN: ROLE_THIRDPARTY_LOGIN
        ROLE_PROJECT_MANAGER: ROLE_VOTER
        ROLE_DOMAIN_MANAGER: ROLE_VOTER
        ROLE_ADMIN:       [ROLE_USER, ROLE_PROJECT_MANAGER, ROLE_DOMAIN_MANAGER]
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            form_login:
                check_path: /api/login
                login_path: /
                username_parameter: username
                password_parameter: password
                provider: fos_userbundle
            logout:
                path: /api/login
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/partial/profile, role: ROLE_USER }
