security:
    encoders:
        Dothiv\BusinessBundle\Entity\User: plaintext

    providers:
        user:
            id: dothiv.businessbundle.service.user

    role_hierarchy:
        ROLE_USER: ~
        ROLE_VOTER:            ROLE_USER
        ROLE_PROJECT_MANAGER:  ROLE_USER
        ROLE_DOMAIN_MANAGER:   ROLE_USER
        ROLE_ADMIN:            [ROLE_VALIDATED, ROLE_PROJECT_MANAGER, ROLE_DOMAIN_MANAGER]
        ROLE_SUPER_ADMIN:      ROLE_ADMIN

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        user:
            pattern:    ^/api/(user|domain|attachment|nonprofit|premium-configurator)
            stateless:  true
            provider:   user
            oauth2:     true

    access_control:
      - { path: ^/api/user, roles: ROLE_USER }
      - { path: ^/api/domain, roles: ROLE_USER }
