parameters:
    dothiv_afilias_importer.service.class: Dothiv\AfiliasImporterBundle\Service\AfiliasImporterService
    dothiv_afilias_importer.service.client.class: Dothiv\AfiliasImporterBundle\Service\AfiliasImporterService

services:
    dothiv_afilias_importer.service:
        class: %dothiv_afilias_importer.service.class%
        argument:
