parameters:
    dothiv.websitebase.assetic.filter.ngmin.class: DotHiv\WebsiteBaseBundle\Assetic\Filter\NgMinFilter
    dothiv.websitebase.assetic.filter.ngmin.bin: /usr/bin/ngmin

services:
    dothiv.websitebase.assetic.filter.ngmin:
        class: %dothiv.websitebase.assetic.filter.ngmin.class%
        tags:
            - { name: assetic.filter, alias: ngmin }
        arguments: [%dothiv.websitebase.assetic.filter.ngmin.bin%]

    dothiv.websitebase.assetic.filter.closureecma5:
        class: %assetic.filter.closure.jar.class%
        tags:
            - { name: assetic.filter, alias: closureecma5 }
        arguments: [%assetic.filter.closure.jar%, %assetic.filter.closure.java%]
        calls:
            - [ setTimeout, [%assetic.filter.closure.timeout%] ]
            - [ setCompilationLevel, [%assetic.filter.closure.compilation_level%] ]
            - [ setLanguage, ['ECMASCRIPT5'] ]
