parameters:
#    dot_hiv_website_company.example.class: DotHiv\WebsiteCompanyBundle\Example

services:
#    dot_hiv_website_company.example:
#        class: %dot_hiv_website_company.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
