services:
    dothiv.premiumconfigurator.controller.page:
        class: Dothiv\PremiumConfiguratorBundle\Controller\PremiumConfiguratorPageController
        arguments:
          - @dothiv.websitebase.cache.request_lastmodified
          - @templating
          - @dothiv.charity.contentful.charity_content
          - "DothivPremiumConfiguratorBundle"
          - %assets_version%
          - @clock
          - %page_lifetime%

    dothiv.premiumconfigurator.controller.preview:
        class: Dothiv\PremiumConfiguratorBundle\Controller\PremiumConfiguratorPreviewController
        arguments:
          - @templating
          - @dothiv.repository.domain
          - @dothiv.repository.banner

    dothiv.premiumconfigurator.api.controller.attachment:
        class: %dothiv.api.controller.attachment.class%
        arguments:
         - @dothiv.premiumconfigurator.service.attachment
         - @security.context
         - @serializer
