dothiv_qlp_landingpage:
    path:     /{locale}/premium-configurator/{subpage}
    defaults:
        _controller: dothiv.premiumconfigurator.controller.page:configuratorPageAction
        subpage: start
