dothiv_premiumconfig_page:
    path:     /{locale}/premium-configurator/{domain}
    defaults:
        _controller: dothiv.premiumconfigurator.controller.page:configuratorPageAction

dothiv_premiumconfig_preview:
    path:     /{locale}/premium-configurator/{domain}/preview
    defaults:
        _controller: dothiv.premiumconfigurator.controller.preview:previewAction

dothiv_premiumconfig_preview_config:
    path:     /{locale}/premium-configurator/{domain}/demo.json
    defaults:
        _controller: dothiv.premiumconfigurator.controller.preview:previewBannerConfigAction

dothiv_premiumconfig_preview_banner:
    path:     /{locale}/premium-configurator/{domain}/{file}
    defaults:
        _controller: dothiv.premiumconfigurator.controller.preview:previewBannerFileAction
    requirements:
        file: ^banner-(center|right|top).html

dothiv_premiumconfig_page_app:
    path:     /{locale}/premium-configurator/{domain}/app/{page}.html
    defaults:
        _controller: dothiv.premiumconfigurator.controller.page:configuratorAppPageAction
