dothiv_qlp_page:
    path:     /{locale}/premium-configurator/{domain}
    defaults:
        _controller: dothiv.premiumconfigurator.controller.page:configuratorPageAction

dothiv_qlp_page_app:
    path:     /{locale}/premium-configurator/{domain}/app/{page}.html
    defaults:
        _controller: dothiv.premiumconfigurator.controller.page:configuratorAppPageAction
