parameters:
    dothiv.premiumconfigurator.service.attachment_store.class: Dothiv\PremiumConfiguratorBundle\Service\AttachmentStoreService

services:
    dothiv.premiumconfigurator.service.attachment:
        class: %dothiv.businessbundle.service.attachment.class%
        arguments:
        - @dothiv.repository.attachment
        - ['image/png', 'image/jpeg', 'image/gif']
        - @dothiv.premiumconfigurator.service.attachment_store

    dothiv.premiumconfigurator.service.attachment_store:
        class: %dothiv.premiumconfigurator.service.attachment_store.class%
        arguments:
        - %dothiv_premium_configurator.attachments%
        - @router
        - @dothiv.websitebase.service.image_scaler
        - %charitydomain%
