parameters:
    dothiv.premiumconfigurator.service.attachment_store.class: Dothiv\PremiumConfiguratorBundle\Service\AttachmentStoreService
    dothiv.premiumconfigurator.mailer.subscription_confirmed.class: Dothiv\PremiumConfiguratorBundle\Service\Mailer\SubscriptionConfirmedMailer
    dothiv.premiumconfigurator.routing.loader.class: Dothiv\PremiumConfiguratorBundle\Routing\RoutingLoader
    dothiv.premiumconfigurator.routing.listener.class: Dothiv\PremiumConfiguratorBundle\Routing\RoutingListener

services:
    dothiv.premiumconfigurator.service.attachment:
        class: %dothiv.businessbundle.service.attachment.class%
        arguments:
        - @dothiv.repository.attachment
        - ['image/png', 'image/jpeg', 'image/gif']
        - @dothiv.premiumconfigurator.service.attachment_store

    dothiv.premiumconfigurator.service.attachment_store:
        class: %dothiv.premiumconfigurator.service.attachment_store.class%
        arguments:
        - %dothiv_premium_configurator.attachments%
        - @router
        - @dothiv.websitebase.service.image_scaler
        - %charitydomain%

    dothiv.premiumconfigurator.mailer.subscription_confirmed:
        class: %dothiv.premiumconfigurator.mailer.subscription_confirmed.class%
        arguments:
        - @dothiv.charity.service.mailer.content

    dothiv.premiumconfigurator.routing.loader:
        class: %dothiv.premiumconfigurator.routing.loader.class%
        tags:
         - { name: routing.loader }

    dothiv.premiumconfigurator.routing.listener:
        class: %dothiv.premiumconfigurator.routing.listener.class%
        arguments:
        - @dothiv.premiumconfigurator.routing.loader
        - @router
        - @doctrine_cache.providers.dothiv_premium_routing_cache
        tags:
        - { name: kernel.event_listener, event: kernel.request, priority: 33 }
