parameters:
    dothiv_contentful.http_client.class: Dothiv\ContentfulBundle\Client\CachingHttpClient
    dothiv_contentful.content.class: Dothiv\ContentfulBundle\Adapter\RepositoryContentAdapter
    dothiv_contentful.asset.class: Dothiv\ContentfulBundle\Adapter\CachingAssetAdapter

services:
    dothiv_contentful.http_client:
        class: %dothiv_contentful.http_client.class%
        arguments:
          - @doctrine_cache.providers.contentful_api_cache

    dothiv_contentful.asset:
        class: %dothiv_contentful.asset.class%
        arguments:
          - @router
          - @dothiv_contentful.repo.asset

    dothiv_contentful.content:
        class: %dothiv_contentful.content.class%
        arguments:
          - @dothiv_contentful.repo.content_type
          - @dothiv_contentful.repo.entry
          - @dothiv_contentful.repo.asset
          - @dothiv_contentful.asset

    dothiv_contentful.routing_loader:
        class: Dothiv\ContentfulBundle\DependencyInjection\RoutingLoader
        tags:
          - { name: routing.loader }
