parameters:
    dothiv_contentful.http_client.class: Dothiv\ContentfulBundle\Client\CachingHttpClient

services:
    dothiv_contentful.http_client:
        class: %dothiv_contentful.http_client.class%
        arguments:
          - @doctrine_cache.providers.contentful_api_cache
