services:
    dothiv.charity.web.controller.index:
        class: Dothiv\CharityWebsiteBundle\Controller\IndexController
        arguments:
          - @templating
          - @dothiv.websitebase.contentful.portals_content
          - "DothivCharityWebsiteBundle"

    dothiv.charity.web.controller.page:
        class: Dothiv\CharityWebsiteBundle\Controller\PageController
        arguments:
          - @templating
          - @dothiv.websitebase.contentful.portals_content
          - "DothivCharityWebsiteBundle"
