# Redirect to default locale: en
dothiv_charity_index_nolang:
    pattern:  /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /en
        permanent: true

dothiv_charity_index:
    pattern:  /{locale}
    defaults:
        _controller: dothiv.charity.web.controller.index:indexAction
    requirements:
        locale:  en|de|ky

# TODO: Implement
dothiv_charity_domain_claim:
    pattern: /{locale}/domain/claim/{token}
    defaults:
        _controller: dothiv.base.web.controller.charity_page:pageAction
        page: domain/claim
    requirements:
        locale:  en|de|ky

dothiv_content_api:
    pattern:  /{locale}/content/{type}
    defaults:
        _controller: dothiv.base.web.controller.charity_page:contentAction
    requirements:
        locale:  en|de|ky
        type: Quote

dothiv_charity_page:
    pattern:  /{locale}/{page}
    defaults:
        _controller: dothiv.base.web.controller.charity_page:pageAction
        page: index
    requirements:
        locale:  en|de|ky
        page: ^[a-zA-Z]+[a-zA-Z/]+[a-zA-Z0-9]+$


