dot_hiv_website_homepage:
    pattern:  /
    defaults: { _controller: DotHivWebsiteBundle:Default:index }

dot_hiv_partial_view1:
    pattern:  /partial/view1
    defaults: { _controller: DotHivWebsiteBundle:Partial:view1 }
