FOS\UserBundle\Model\User:
    exclusion_policy: ALL
    properties:
        username:
            expose: true
        usernameCanonical:
            expose: true
        email:
            expose: true
        emailCanonical:
            expose: true
        lastLogin:
            expose: true
        roles:
            expose: true
