dot_hiv_website_charity_app:
    pattern:  /
    host:     dothiv.bp
    defaults: { _controller: DotHivWebsiteCharityBundle:Default:index }

dot_hiv_website_charity_partial_home:
    pattern:  /partial/home
    host:     dothiv.bp
    defaults: { _controller: DotHivWebsiteCharityBundle:Partial:home }

dot_hiv_website_charity_partial_login:
    pattern:  /partial/login
    host:     dothiv.bp
    defaults: { _controller: DotHivWebsiteCharityBundle:Partial:login }

dot_hiv_website_chartiy_partial_register:
    pattern: /partial/register
    host: dothiv.bp
    defaults: { _controller: DotHivWebsiteChartyBundle:Partial:register }

dot_hiv_website_charity_partial_profile:
    pattern:  /partial/profile
    host:     dothiv.bp
    defaults: { _controller: DotHivWebsiteCharityBundle:Partial:profile }