dot_hiv_website_charity_app:
    pattern:  /
    defaults: { _controller: DotHivWebsiteCharityBundle:Default:index }

dot_hiv_website_charity_partial_home:
    pattern:  /partial/home
    defaults: { _controller: DotHivWebsiteCharityBundle:Partial:home }

dot_hiv_website_charity_partial_login:
    pattern:  /partial/login
    defaults: { _controller: DotHivWebsiteCharityBundle:Partial:login }

dot_hiv_website_chartiy_partial_registration:
    pattern: /partial/registration
    defaults: { _controller: DotHivWebsiteCharityBundle:Partial:registration }

dot_hiv_website_charity_partial_profile:
    pattern:  /partial/profile
    defaults: { _controller: DotHivWebsiteCharityBundle:Partial:profile }

dot_hiv_website_charity_partial_profile_summary:
    pattern:  /partial/profile/summary
    defaults: { _controller: DotHivWebsiteCharityBundle:Partial:profileSummary }

dot_hiv_website_charity_partial_profile_edit:
    pattern:  /partial/profile/edit
    defaults: { _controller: DotHivWebsiteCharityBundle:Partial:profileEdit }

dot_hiv_website_charity_partial_profile_projects:
    pattern:  /partial/profile/projects
    defaults: { _controller: DotHivWebsiteCharityBundle:Partial:profileProjects }
