dot_hiv_website_charity_app:
    pattern:  /
    defaults: { _controller: DotHivWebsiteCharityBundle:Default:index }

dot_hiv_website_charity_partial_home:
    pattern:  /partial/home
    defaults: { _controller: DotHivWebsiteCharityBundle:Partial:home }

dot_hiv_website_charity_partial_login:
    pattern:  /partial/login
    defaults: { _controller: DotHivWebsiteCharityBundle:Partial:login }

dot_hiv_website_charity_partial_mock:
    pattern: /partial/mock
    defaults: { _controller: DotHivWebsiteCharityBundle:Partial:mock }

dot_hiv_website_charity_partial_about:
    pattern:  /partial/about
    defaults: { _controller: DotHivWebsiteCharityBundle:Partial:about }

dot_hiv_website_charity_partial_about_idea:
    pattern:  /partial/about/idea
    defaults: { _controller: DotHivWebsiteCharityBundle:Partial:aboutIdea }

dot_hiv_website_charity_partial_profile:
    pattern:  /partial/profile
    defaults: { _controller: DotHivWebsiteCharityBundle:Partial:profile }

dot_hiv_website_charity_partial_profile_summary:
    pattern:  /partial/profile/summary
    defaults: { _controller: DotHivWebsiteCharityBundle:Partial:profileSummary }

dot_hiv_website_charity_partial_profile_edit:
    pattern:  /partial/profile/edit
    defaults: { _controller: DotHivWebsiteCharityBundle:Partial:profileEdit }

dot_hiv_website_charity_partial_profile_projects:
    pattern:  /partial/profile/projects
    defaults: { _controller: DotHivWebsiteCharityBundle:Partial:profileProjects }

dot_hiv_website_charity_partial_profile_domains:
    pattern:  /partial/profile/domains
    defaults: { _controller: DotHivWebsiteCharityBundle:Partial:profileDomains }

dot_hiv_website_charity_partial_profile_domain_edit:
    pattern:  /partial/profile/domain/edit
    defaults: { _controller: DotHivWebsiteCharityBundle:Partial:profileDomainEdit }

dot_hiv_website_charity_partial_profile_votes:
    pattern:  /partial/profile/votes
    defaults: { _controller: DotHivWebsiteCharityBundle:Partial:profileVotes }

dot_hiv_website_charity_partial_profile_comments:
    pattern:  /partial/profile/comments
    defaults: { _controller: DotHivWebsiteCharityBundle:Partial:profileComments }

dot_hiv_website_charity_partial_profile_domain_claim:
    pattern:  /partial/profile/domain/claim
    defaults: { _controller: DotHivWebsiteCharityBundle:Partial:profileDomainClaim }
