parameters:
#    dot_hiv_website.example.class: DotHiv\WebsiteCharityBundle\Example

services:
#    dot_hiv_website_charity.example:
#        class: %dot_hiv_website_charity.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
