parameters:
    dothiv.repository.banner.entity: 'DothivBusinessBundle:Banner'

services:
    dothiv.repository.banner:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory_service: doctrine
        factory_method: getRepository
        arguments: [ %dothiv.repository.banner.entity% ]
