parameters:
    clickcounter.class: Dothiv\BusinessBundle\Service\ClickCounterConfig
    dothiv.businessbundle.service.clock.class: Dothiv\BusinessBundle\Service\Clock
    dothiv.businessbundle.service.user.class: Dothiv\BusinessBundle\Service\UserService
    dothiv.businessbundle.service.attachment.class: Dothiv\BusinessBundle\Service\AttachmentService
    registration.class: Dothiv\BusinessBundle\Service\Registration
    clickcounter.authorization.username: %clickcounter_auth_username%
    clickcounter.authorization.password: %clickcounter_auth_password%
    clickcounter.base_url: %clickcounter_base_url%

services:
    clickcounter:
        class: %clickcounter.class%
        arguments: ["@service_container","@templating","@translator","@doctrine.orm.entity_manager","@mailer"]
    registration:
        class: %registration.class%
        arguments:
        - @doctrine.orm.entity_manager
        - @event_dispatcher

    clock:
        class: %dothiv.businessbundle.service.clock.class%
        arguments:
        - %dothiv_business.clock_expr%
        - @event_dispatcher

    dothiv.businessbundle.service.user:
        class: %dothiv.businessbundle.service.user.class%
        arguments:
        - @dothiv.repository.user
        - @dothiv.repository.user_token
        - @clock
        - @event_dispatcher

    dothiv.businessbundle.service.attachment:
        class: %dothiv.businessbundle.service.attachment.class%
        arguments:
        - @dothiv.repository.attachment
        - %dothiv_business.attachment_location%
