parameters:
#    dot_hiv_business.example.class: DotHiv\BusinessBundle\Example

services:
#    dot_hiv_business.example:
#        class: %dot_hiv_business.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    dothiv.businessbundle.listener.request:
        class: DotHiv\BusinessBundle\Listener\LocaleListener
        tags: [{ name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: -255 }]
        arguments: [ @service_container ]
