parameters:
#    dot_hiv_business.example.class: DotHiv\BusinessBundle\Example

services:
#    dot_hiv_business.example:
#        class: %dot_hiv_business.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
