parameters:
    clickcounter.class: Dothiv\BusinessBundle\Service\ClickCounterConfig
    dothiv.businessbundle.service.clock.class: Dothiv\BusinessBundle\Service\Clock
    dothiv.businessbundle.service.user.class: Dothiv\BusinessBundle\Service\UserService
    dothiv.businessbundle.service.attachment.class: Dothiv\BusinessBundle\Service\AttachmentService
    registration.class: Dothiv\BusinessBundle\Service\Registration

services:
    clickcounter:
        class: %clickcounter.class%
        arguments:
        - %dothiv_business.clickcounter%
        - @dothiv.business.contentful.clickcounter_content

    registration:
        class: %registration.class%
        arguments:
        - @doctrine.orm.entity_manager
        - @event_dispatcher

    clock:
        class: %dothiv.businessbundle.service.clock.class%
        arguments:
        - %dothiv_business.clock_expr%
        - @event_dispatcher

    dothiv.businessbundle.service.user:
        class: %dothiv.businessbundle.service.user.class%
        arguments:
        - @dothiv.repository.user
        - @dothiv.repository.user_token
        - @clock
        - @event_dispatcher

    dothiv.businessbundle.service.attachment:
        class: %dothiv.businessbundle.service.attachment.class%
        arguments:
        - @dothiv.repository.attachment
        - %dothiv_business.attachment_location%

    dothiv.business.contentful.clickcounter_content:
        class: %dothiv.websitebase.contentful.content.class%
        arguments:
            - @dothiv_contentful.content
            - @dothiv.websitebase.contentful.view_builder
            - %contenful_space_clickcounter%
