parameters:
    clickcounter.class: DotHiv\BusinessBundle\Service\ClickCounterConfig
    dns.class: DotHiv\BusinessBundle\Service\DnsConfig
    dns.reseller: %dns_reseller%
    dns.password: %dns_password%
    dns.cid: %dns_cid%
    dns.nameserver: %dns_nameserver%
    clickcounter.authorization.username: %clickcounter_auth_username%
    clickcounter.authorization.password: %clickcounter_auth_password%
    clickcounter.base_url: %clickcounter_base_url%

services:
    dns:
        class: %dns.class%
        arguments: ["@service_container","@mailer"]
    clickcounter:
        class: %clickcounter.class%
        arguments: ["@service_container","@templating","@translator","@doctrine.orm.entity_manager","@mailer"]
